spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

    open-in-view: false

  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: never

jwt:
  secret: ${JWT_SECRET}
  expiration-hours: 2

logging:
  level:
    root: INFO
    br.com.jardelcell.inventory: INFO
