spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

    open-in-view: false

  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: never

jwt:
  secret: ${JWT_SECRET}
  expiration-hours: 2

logging:
  level:
    root: INFO
    br.com.jardelcell.inventory: INFO

app:
  bootstrap:
    admin:
      full-name: ${ADMIN_FULL_NAME}
      email: ${ADMIN_EMAIL}
      password: ${ADMIN_PASSWORD}

    employee1:
      full-name: ${EMPLOYEE_1_FULL_NAME}
      email: ${EMPLOYEE_1_EMAIL}
      password: ${EMPLOYEE_1_PASSWORD}

    employee2:
      full-name: ${EMPLOYEE_2_FULL_NAME}
      email: ${EMPLOYEE_2_EMAIL}
      password: ${EMPLOYEE_2_PASSWORD}
