spring:
  application:
    name: inventory-api

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

info:
  app:
    name: Inventory API
    description: Backend API for JardelCell inventory management.
    version: 1.0.0
